### ISSUE TITLE
No error message when password is wrong

### ISSUE THREAD

**Issue by Jonathanm10** [sephii/taxi-zebra#1]
``````
Traceback (most recent call last):
  File "/usr/bin/taxi", line 9, in <module>
    load_entry_point('taxi==4.0.0b3', 'console_scripts', 'taxi')()
  File "/usr/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click-3.3-py3.4.egg/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/taxi/commands/update.py", line 27, in update
    backend_projects = backend.get_projects()
  File "/usr/lib/python3.4/site-packages/taxi_zebra/backend.py", line 20, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/taxi_zebra/backend.py", line 95, in get_projects
    response = self._session.get(projects_url).json()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)```
``````

**Comment by sephii** [comment]
Seems to be fixed now, feel free to reopen if that's not the case.
